version: "3.9"

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - backend
    container_name: busca_certa-manager
    volumes:
      - .:/node_app/app
    command: /bin/sh -c "chmod +x entrypoint.sh && /node_app/app/entrypoint.sh"
    env_file:
      - .env

networks:
  backend:
    name: busca_certa-backend_network
    external: true
